---
title: Taxonomic language distances
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}

# load packages
library(rmarkdown)
library(knitr)
library(tidyverse)
library(here)
library(R.matlab)
library(dendextend)
library(ggdendro)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

Language data
```{r}
LANGUAGE_PATH <- here("data/processed/animal_distances_wiki.csv")
language_data <- read_csv(LANGUAGE_PATH) %>%
  spread(word2, language_similarity) %>%
  select(-word1)

all_corrs_mat_langs <- as.matrix(language_data)
rownames(all_corrs_mat_langs) <- colnames(language_data)
```


Taxonomic data
```{r}
KEY_PATH <- here("data/raw/animal_keys.mat")
animal_labels <- readMat(KEY_PATH) %>%
  flatten() %>%
  unlist() %>%
  as.character()  %>%
  .[30:59] # 1-29 are objects (practice round)

TAXONOMIC_PATH <- here("data/raw/taxonomy_matrix.mat")
taxonomic_data <- readMat(TAXONOMIC_PATH)[[1]]  

colnames(taxonomic_data) <- animal_labels
rownames(taxonomic_data) <- animal_labels
```

Taxonomic and Language Dendrograms
```{r}
lang_clust <- all_corrs_mat_langs %>% 
  dist() %>% 
  hclust() 

taxo_clust <- taxonomic_data %>%
    dist() %>% 
    hclust()

ggdendro::ggdendrogram(lang_clust, rotate = T) +
  ggtitle("Language")
ggdendro::ggdendrogram(taxo_clust, rotate = T) +
  ggtitle("Taxonomy")
```

Comparing dendrogram
```{r}
dends <- dendlist(as.dendrogram(lang_clust), as.dendrogram(taxo_clust))
tanglegram(dends, common_subtrees_color_branches = TRUE, highlight_branches_lwd = F)
```

Pairwise correlations
```{r}
language_long <- all_corrs_mat_langs %>%
  as.data.frame() %>%
  rownames_to_column("animal1") %>%
  gather("animal2", "similarity", -animal1) %>%
  mutate(sim_type = "language")

taxonomic_long <- taxonomic_data %>%
  as.data.frame() %>%
  rownames_to_column("animal1") %>%
  gather("animal2", "similarity", -animal1) %>%
  mutate(sim_type = "taxonomy")

tidy_long <- bind_rows(taxonomic_long, language_long) %>%
  filter(animal1 < animal2) %>%
  spread(sim_type, similarity) %>%
    mutate(taxonomic_group = case_when(taxonomy < -400 ~ 1,
                                     taxonomy > -200 ~ 3,
                                     TRUE ~ 2)) 

ggplot(tidy_long, aes(x = taxonomy, y = language )) +
  geom_point() + 
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(tidy_long, aes(x = taxonomy, y = language )) +
  geom_point() + 
  facet_wrap(~ taxonomic_group, scale = "free") +
  geom_smooth(method = "lm") +
  theme_classic()
```

```{r}
tidy_long %>%
  arrange(taxonomic_group) %>%
  DT::datatable()

```
